Added UZBL Configs

diff --git a/sign b/sign
--- a/sign
+++ b/sign
@@ -12,15 +12,22 @@ if [ "$#" -ne "1" ]; then
 	exit 1
 fi
 
+# Pull the Latest Changes
+
 # Commit Current Changes
 date -u +%s > .date
 git add .date
-git commit -m "$1"
+git commit -m "$1" >/dev/null 2>&1
 
 # Sign and Commit Signature
 hash_commit "HEAD" > .hash
 rm -f .sig
 gpg -bo .sig .hash
 git add .hash .sig
-git commit -m "Signing Commit"
-git push origin master
+git commit -m "Signing Commit" >/dev/null 2>&1
+git push origin master >/dev/null 2>&1
+if [ "$?" -ne "0" ]; then
+	echo "Failed To Push Commit!" >&2
+	exit 1
+fi
+exit 0
