More Integrity Changes

diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -1,3 +1,12 @@
 #!/bin/sh
-echo "Invalid Directory Signature"
+DIR="$(dirname "$(readlink -f "$0")")"
+cd $DIR
+. ./integrity
+
+# Required Programs
+require_all
+
+# Get the latest Commits
+gpg --verify .sig .hash
+echo "Invalid Directory Signature" >&2
 exit 1
