Better Agent Choice Support

diff --git a/lib/mod/agent b/lib/mod/agent
--- a/lib/mod/agent
+++ b/lib/mod/agent
@@ -33,22 +33,33 @@ agent_pin_program () {
   path_bin pinentry
 }
 
+# Prints the command for running the gpg-agent
+agent_gpg () {
+  mkdir -p "$HOME/.gnupg"
+  echo "pcsc-driver $(agent_find_pcsc)" > "$HOME/.gnupg/scdaemon.conf"
+  echo "card-timeout 5" >> "$HOME/.gnupg/scdaemon.conf"
+  echo "disable-ccid" >> "$HOME/.gnupg/scdaemon.conf"
+  local PIN_PROG="$(agent_pin_program)"
+  if [ "$?" -ne "0" ]; then
+    echo "Couldn't select gpg-agent: no pinentry program" >&2
+  else
+    agent_cmd gpg-agent --pinentry-program "$PIN_PROG" --daemon --enable-ssh-support && return 0
+  fi
+  return 1
+}
+
+# Prints the command for running the ssh-agent
+agent_ssh () {
+  agent_cmd ssh-agent
+}
+
 # Determine which agent to use
 agent_which () {
-  [ "$(hostname -s)" = "fantom" ] && agent_cmd ssh-agent && return 0
-  (info_ws && ! info_root) && {
-    mkdir -p "$HOME/.gnupg"
-    echo "pcsc-driver $(agent_find_pcsc)" > "$HOME/.gnupg/scdaemon.conf"
-    echo "card-timeout 5" >> "$HOME/.gnupg/scdaemon.conf"
-    echo "disable-ccid" >> "$HOME/.gnupg/scdaemon.conf"
-    local PIN_PROG="$(agent_pin_program)"
-    if [ "$?" -ne "0" ]; then
-      echo "Couldn't select gpg-agent: no pinentry program" >&2
-    else
-      agent_cmd gpg-agent --pinentry-program "$PIN_PROG" --daemon --enable-ssh-support && return 0
-    fi
-  }
-  agent_cmd ssh-agent && return 0
+  [ "$1" = "ssh" ] && agent_ssh && return 0
+  [ "$1" = "gpg" ] && agent_gpg && return 0
+  [ "$(hostname -s)" = "fantom" ] && agent_ssh && return 0
+  (info_ws && ! info_root) && agent_gpg && return 0
+  agent_ssh && return 0
   echo "Failed to find an agent" >&2
   return 1
 }
@@ -89,7 +100,7 @@ agent_spawn () {
 
 # Automatically determines which agent to use and starts it if necessary
 agent_auto () {
-  local AGENT=$(agent_which)
+  local AGENT=$(agent_which $@)
   agent_proper
   agent_running || agent_env
   agent_proper
