Overhauled Module Array Access

diff --git a/lib/mod/core b/lib/mod/core
--- a/lib/mod/core
+++ b/lib/mod/core
@@ -15,15 +15,23 @@ symlink () {
 
 # Get the path to the temporary directory
 dir_tmp () {
-  local DIRS;
-  to_array DIRS "/dev/shm /run/shm /tmp /var/tmp"
-  for I in $DIRS; do
-	[ -w "$I" ] && (mount | grep '\(tmpfs\|ramfs\)' | grep $I >/dev/null) && DIR_TMP="$I/$USER" && break
-  done
-  [ "$DIR_TMP" = "" ] && (echo "Failed to find a temporary folder" >&2) && return 1
+  local DIR_TMP
+  dir_tmp_tryall
+  [ "$DIR_TMP" = "" ] && { echo "Failed to find a temporary folder" >&2; return 1; }
   [ ! -d "$DIR_TMP" ] && mkdir "$DIR_TMP" && chmod 0700 "$DIR_TMP"
   symlink "$DIR_TMP" "$HOME/.tmp"
   echo "$DIR_TMP"
+}
+dir_tmp_tryall() {
+  dir_tmp_one "/dev/shm" && return 0
+  dir_tmp_one "/run/shm" && return 0
+  dir_tmp_one "/tmp" && return 0
+  dir_tmp_one "/var/tmp" && return 0
+}
+dir_tmp_one () {
+	[ -w "$1" ] || return 1
+  mount | grep '\(tmpfs\|ramfs\)' | grep $1 >/dev/null || return 1
+  DIR_TMP="$1/$USER"
 }
 
 # Tests to see if a binary exists in the path
