Refactoring

diff --git a/base/mod/core b/base/mod/core
--- a/base/mod/core
+++ b/base/mod/core
@@ -7,19 +7,16 @@ function run_quiet {
 
 # Get the path to the temporary directory
 function dir_tmp {
-  if [ "$DIR_TMP" = "" ] || [ ! -d "$DIR_TMP" ]; then
-    local DIRS;
-    to_array DIRS "/dev/shm /run/shm /tmp /var/tmp"
-    for I in $DIRS; do
-	  [ -w "$I" ] && (mount | grep '\(tmpfs\|ramfs\)' | grep $I >/dev/null) && DIR_TMP="$I/$USER" && break
-    done
-    [ "$DIR_TMP" = "" ] && (echo "Failed to find a temporary folder" >&2) && return 1
-    [ ! -d "$DIR_TMP" ] && mkdir "$DIR_TMP" && chmod 0700 "$DIR_TMP"
-    if [ ! -h "$HOME/.tmp" ]; then
-        [ -e "$HOME/.tmp" ] && rm -rf "$HOME/.tmp"
-        ln -s "$DIR_TMP" "$HOME/.tmp"
-    fi
-    export DIR_TMP
+  local DIRS;
+  to_array DIRS "/dev/shm /run/shm /tmp /var/tmp"
+  for I in $DIRS; do
+	[ -w "$I" ] && (mount | grep '\(tmpfs\|ramfs\)' | grep $I >/dev/null) && DIR_TMP="$I/$USER" && break
+  done
+  [ "$DIR_TMP" = "" ] && (echo "Failed to find a temporary folder" >&2) && return 1
+  [ ! -d "$DIR_TMP" ] && mkdir "$DIR_TMP" && chmod 0700 "$DIR_TMP"
+  if [ ! -h "$HOME/.tmp" ]; then
+    [ -e "$HOME/.tmp" ] && rm -rf "$HOME/.tmp"
+    ln -s "$DIR_TMP" "$HOME/.tmp"
   fi
   echo "$DIR_TMP"
 }
@@ -37,10 +34,9 @@ function path_hasbin {
 
 # Add to the path if the DIR doesn't exist
 function path_add {
-    if [ "$(echo "$PATH" | grep "$1" 2>/dev/null)" = "" ]; then
-        PATH="${PATH}:$1"
-        export PATH
-    fi
+  if [ "$(echo "$PATH" | grep "$1" 2>/dev/null)" = "" ]; then
+    export PATH="${PATH}:$1"
+  fi
 }
 
 # Wraps the command in sudo if sudo exists and runs it
diff --git a/base/mod/os b/base/mod/os
--- a/base/mod/os
+++ b/base/mod/os
@@ -2,16 +2,14 @@
 
 # Returns the issue of the operating system
 function os_issue {
-  if [ "$OS_ISSUE" = "" ]; then
-    OS_ISSUE="$(cat /etc/issue 2>/dev/null)"
-    [ "$OS_ISSUE" = "" ] && echo "Failed to get OS Issue" >&2 && return 1
-    export OS_ISSUE
-  fi
-  echo "$OS_ISSUE"
+  local OS_ISSUE
+  OS_ISSUE="$(cat /etc/issue 2>/dev/null)" && { echo "$OS_ISSUE"; return 0; }
+  echo "Failed to get OS Issue" >&2
+  return 1
 }
 
 function os_info {
-    uname -a
+  uname -a
 }
 
 # Determines whether the os info matches the regex provided
