Attempt to Better Fix Shell Compat Issues

diff --git a/lib/loader b/lib/loader
--- a/lib/loader
+++ b/lib/loader
@@ -2,43 +2,30 @@
 
 # Returns the shell executing the current script
 shell () {
-  basename "$(ps hp $$ | grep "$$" | awk '{print $5}' | sed 's/-//')"
-}
-
-# Creates an array from the name of the variable and values
-to_array () {
-  ([ "$#" -lt "1" ] || [ "$#" -gt "2" ]) && return 1
-
-  # Read in the array data
-  local DATA
-  if [ "$#" -eq "1" ]; then
-    DATA="$(cat -)"
-  else
-    DATA="$2"
-  fi
-
-  # Convert the data into an array
-  if [ "$(shell)" = "zsh" ]; then
-    eval "$1=($DATA)"
-  elif [ "$(shell)" = "sh" ] || [ "$(shell)" = "bash" ]; then
-    eval "$1=\"$DATA\""
-  else
-    return 1
-  fi
+  local SHELL;
+  SHELL="$(basename "$(ps hp $$ | grep "$$" | awk '{print $5}' | sed 's/-//')")"
+  basename "$(readlink -f "$(which $SHELL)")"
 }
 
 # Determines the top level configuration directory
-dir_conf () {
-  local FILES
-  to_array FILES "$1 $HOME/.zshrc $HOME/.bashrc $HOME/.xinitrc"
-  for FILE in $FILES; do
-    cd "$(dirname "$(readlink -f "$FILE")")" 2>/dev/null || continue
-    DIR_CONF="$(git rev-parse --show-toplevel 2>/dev/null)" || continue
-    echo "$DIR_CONF"
-    return 0
-  done
-  echo "Failed to find the configuration directory" >&2
-  return 1
+dir_try () {
+  cd "$(dirname "$(readlink -f "$1")")" 2>/dev/null || return 1
+  DIR_CONF="$(git rev-parse --show-toplevel 2>/dev/null)" || return 1
+  echo "$DIR_CONF"
+}
+dir_conf () {(
+    dir_try "$1" && return 0
+    dir_try "$HOME/.zshrc" && return 0
+    dir_try "$HOME/.bashrc" && return 0
+    dir_try "$HOME/.xinitrc" && return 0
+    echo "Failed to find the configuration directory" >&2
+    return 1
+)}
+
+# Loads the shell specific fixes
+. "$(dir_conf "$0")/lib/fixes.$(shell)" 2>/dev/null || {
+  echo "Failed to load the fixes for the current shell" >&2
+  exit 1
 }
 
 # Allows the functions to be reloaded at any time
@@ -48,12 +35,13 @@ reload_all () {
 
 # Source Modules
 load_all () {
+  [ "$#" -ge "1" ] || return 1
   local DIRCONF; local MODS;
   DIRCONF="$(dir_conf "$0")" || return 1
-  to_array MODS "$(find "$DIRCONF/lib/mod" -type f)"
+  to_array MODS "$(find "$DIRCONF/$1" -type f)"
   for M in $MODS; do
     [ "$(echo "$M" | grep '\(~$\|^#\)')" != "" ] && continue
     . "$M" || { echo "Failed to load module $M"; return 1; }
   done
 }
-load_all
+load_all lib/mod
