Add variable store without subshell

diff --git a/lib/loader b/lib/loader
--- a/lib/loader
+++ b/lib/loader
@@ -1,5 +1,18 @@
 #!/usr/bin/env sh
 
+# Stores the output of the command into a variable without a subshell
+svar () {
+  local VAR; local TMP; local RET;
+  VAR="$1"
+  shift 1
+  TMP="$(mktemp)"
+  $@ >"$TMP"
+  RET="$?"
+  read "$VAR" <"$TMP"
+  rm "$TMP"
+  return "$RET"
+}
+
 # Returns the shell executing the current script
 shell () {
   local LSHELL;
@@ -17,19 +30,22 @@ dir_try () {
   DIR_BIN="$(readlink -f "$1" 2>/dev/null)" || return 1
   cd "$(dirname "$DIR_BIN")" 2>/dev/null || return 1
   DIR_CONF="$(git rev-parse --show-toplevel 2>/dev/null)" || return 1
+  export DIR_CONF
   echo "$DIR_CONF"
 }
-dir_conf () {(
-    dir_try "$1" && return 0
-    dir_try "$HOME/.zshrc" && return 0
-    dir_try "$HOME/.bashrc" && return 0
-    dir_try "$HOME/.xinitrc" && return 0
-    echo "Failed to find the configuration directory" >&2
-    return 1
-)}
+dir_conf () {
+  [ -z "$DIR_CONF" ] || { echo "$DIR_CONF"; return 0; }
+  dir_try "$1" && return 0
+  dir_try "$HOME/.zshrc" && return 0
+  dir_try "$HOME/.bashrc" && return 0
+  dir_try "$HOME/.xinitrc" && return 0
+  echo "Failed to find the configuration directory" >&2
+  return 1
+}
 
 # Loads the shell specific fixes
-. "$(dir_conf "$0")/lib/fixes.$(shell_nov)" 2>/dev/null || {
+svar DIRCONF dir_conf "$0" || return 1
+. "$DIRCONF/lib/fixes.$(shell_nov)" 2>/dev/null || {
   echo "Failed to load the fixes for the current shell" >&2
   exit 1
 }
@@ -58,7 +74,7 @@ load_one () {
 load_all () {
   [ "$#" -ge "1" ] || return 1
   local DIRCONF; local MODS;
-  DIRCONF="$(dir_conf "$0")" || return 1
+  svar DIRCONF dir_conf || return 1
   array_from_str MODS "$(find "$DIRCONF/$1" -type f)"
   array_forall MODS load_one
 }
