Fixed Directory Detector

diff --git a/base/loader b/base/loader
--- a/base/loader
+++ b/base/loader
@@ -1,5 +1,20 @@
 #!/usr/bin/env sh
 
+
+function dir_conf_try {
+  cd "$(dirname "$(readlink -f "$1")")" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null && return 0
+  return 1
+}
+
+# Determines the top level configuration directory
+function dir_conf {
+  dir_conf_try "$1" && return 0
+  dir_conf_try "~/.zshrc" && return 0
+  dir_conf_try "~/.bashrc" && return 0
+  echo "Failed to find the configuration directory" >&2
+  return 1
+}
+
 # Creates an array from the name of the variable and values
 function to_array {
   ([ "$#" -lt "1" ] || [ "$#" -gt "2" ]) && return 1
@@ -21,7 +36,7 @@ function to_array {
 }
 
 # Source Modules
-to_array MODS "$(find $CONF/base/mod -type f)"
+to_array MODS "$(find $(dir_conf $0)/base/mod -type f)"
 for M in $MODS; do
   [ "$(echo "$M" | grep '\(~$\|^#\)')" != "" ] && continue
   . "$M"
